import type { MockJob } from "@/types/findJobs";

export const mockJobs: MockJob[] = [
  {
    id: "vercel-senior-frontend",
    company: "Vercel",
    role: "Senior Frontend Engineer",
    matchScore: 94,
    salaryEstimate: "$160k - $200k",
    source: "Search",
    dateFound: "2 hours ago",
    foundAtDaysAgo: 0,
  },
  {
    id: "stripe-staff-ui",
    company: "Stripe",
    role: "Staff UI Engineer",
    matchScore: 88,
    salaryEstimate: "$180k - $240k",
    source: "Search",
    dateFound: "Yesterday",
    foundAtDaysAgo: 1,
  },
  {
    id: "linear-product-engineer",
    company: "Linear",
    role: "Product Engineer",
    matchScore: 96,
    salaryEstimate: "$150k - $190k",
    source: "Search",
    dateFound: "Yesterday",
    foundAtDaysAgo: 1,
  },
  {
    id: "notion-frontend-developer",
    company: "Notion",
    role: "Frontend Developer",
    matchScore: 72,
    salaryEstimate: "$130k - $170k",
    source: "URL",
    dateFound: "2 days ago",
    foundAtDaysAgo: 2,
  },
  {
    id: "openai-design-engineer",
    company: "OpenAI",
    role: "Design Engineer",
    matchScore: 91,
    salaryEstimate: "$200k - $280k",
    source: "Search",
    dateFound: "3 days ago",
    foundAtDaysAgo: 3,
  },
  {
    id: "figma-editor-engineer",
    company: "Figma",
    role: "Software Engineer, Editor",
    matchScore: 85,
    salaryEstimate: "$170k - $220k",
    source: "Search",
    dateFound: "4 days ago",
    foundAtDaysAgo: 4,
  },
  {
    id: "anthropic-product-platform",
    company: "Anthropic",
    role: "Product Platform Engineer",
    matchScore: 82,
    salaryEstimate: "$190k - $250k",
    source: "Search",
    dateFound: "5 days ago",
    foundAtDaysAgo: 5,
  },
  {
    id: "airbnb-web-platform",
    company: "Airbnb",
    role: "Web Platform Engineer",
    matchScore: 78,
    salaryEstimate: "$165k - $215k",
    source: "Search",
    dateFound: "6 days ago",
    foundAtDaysAgo: 6,
  },
  {
    id: "github-frontend-infra",
    company: "GitHub",
    role: "Frontend Infrastructure Engineer",
    matchScore: 74,
    salaryEstimate: "$155k - $210k",
    source: "Search",
    dateFound: "1 week ago",
    foundAtDaysAgo: 7,
  },
  {
    id: "shopify-staff-frontend",
    company: "Shopify",
    role: "Staff Frontend Developer",
    matchScore: 69,
    salaryEstimate: "$145k - $195k",
    source: "Search",
    dateFound: "1 week ago",
    foundAtDaysAgo: 8,
  },
  {
    id: "datadog-product-ui",
    company: "Datadog",
    role: "Product UI Engineer",
    matchScore: 66,
    salaryEstimate: "$150k - $205k",
    source: "Search",
    dateFound: "9 days ago",
    foundAtDaysAgo: 9,
  },
  {
    id: "asana-frontend-engineer",
    company: "Asana",
    role: "Frontend Engineer",
    matchScore: 64,
    salaryEstimate: "$140k - $185k",
    source: "Search",
    dateFound: "10 days ago",
    foundAtDaysAgo: 10,
  },
  {
    id: "canva-design-systems",
    company: "Canva",
    role: "Design Systems Engineer",
    matchScore: 62,
    salaryEstimate: "$135k - $180k",
    source: "Search",
    dateFound: "11 days ago",
    foundAtDaysAgo: 11,
  },
  {
    id: "dropbox-web-experience",
    company: "Dropbox",
    role: "Web Experience Engineer",
    matchScore: 59,
    salaryEstimate: "$130k - $175k",
    source: "Search",
    dateFound: "12 days ago",
    foundAtDaysAgo: 12,
  },
  {
    id: "monday-product-frontend",
    company: "monday.com",
    role: "Product Frontend Engineer",
    matchScore: 57,
    salaryEstimate: "$125k - $165k",
    source: "Search",
    dateFound: "13 days ago",
    foundAtDaysAgo: 13,
  },
  {
    id: "loom-growth-engineer",
    company: "Loom",
    role: "Growth Frontend Engineer",
    matchScore: 55,
    salaryEstimate: "$120k - $160k",
    source: "Search",
    dateFound: "2 weeks ago",
    foundAtDaysAgo: 14,
  },
  {
    id: "miro-collaboration-ui",
    company: "Miro",
    role: "Collaboration UI Engineer",
    matchScore: 53,
    salaryEstimate: "$125k - $170k",
    source: "Search",
    dateFound: "2 weeks ago",
    foundAtDaysAgo: 15,
  },
  {
    id: "retool-frontend-product",
    company: "Retool",
    role: "Frontend Product Engineer",
    matchScore: 51,
    salaryEstimate: "$135k - $180k",
    source: "Search",
    dateFound: "16 days ago",
    foundAtDaysAgo: 16,
  },
  {
    id: "zapier-frontend-platform",
    company: "Zapier",
    role: "Frontend Platform Engineer",
    matchScore: 49,
    salaryEstimate: "$120k - $155k",
    source: "Search",
    dateFound: "17 days ago",
    foundAtDaysAgo: 17,
  },
  {
    id: "brex-web-engineer",
    company: "Brex",
    role: "Web Engineer",
    matchScore: 47,
    salaryEstimate: "$130k - $175k",
    source: "Search",
    dateFound: "18 days ago",
    foundAtDaysAgo: 18,
  },
  {
    id: "ramp-product-engineer",
    company: "Ramp",
    role: "Product Engineer, Frontend",
    matchScore: 45,
    salaryEstimate: "$145k - $190k",
    source: "Search",
    dateFound: "19 days ago",
    foundAtDaysAgo: 19,
  },
  {
    id: "mercury-frontend",
    company: "Mercury",
    role: "Frontend Engineer",
    matchScore: 43,
    salaryEstimate: "$125k - $170k",
    source: "Search",
    dateFound: "20 days ago",
    foundAtDaysAgo: 20,
  },
  {
    id: "hashicorp-ui-engineer",
    company: "HashiCorp",
    role: "UI Engineer",
    matchScore: 41,
    salaryEstimate: "$120k - $165k",
    source: "Search",
    dateFound: "3 weeks ago",
    foundAtDaysAgo: 21,
  },
  {
    id: "twilio-console-frontend",
    company: "Twilio",
    role: "Console Frontend Engineer",
    matchScore: 39,
    salaryEstimate: "$115k - $155k",
    source: "Search",
    dateFound: "3 weeks ago",
    foundAtDaysAgo: 22,
  },
];
